def caratula():
    print("  @@@@@@@@@@@@@@@@@@@@@@@@@@@@  ".center(80))
    print("  @@@@@@@@@@@@@@@@@@@@@@@@@@@@  ".center(80))
    print("  @@   @@   @@    @@   @@   @@  ".center(80))
    print(" @@    @@   @@    @@   @@    @@ ".center(80))
    print("@@@   @@    @@    @@    @@   @@@".center(80))
    print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@".center(80))
    print("@@   @@@    @@    @@    @@@   @@".center(80))
    print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@".center(80))
    print(" @@@@@@@@@@@@@ @@  @@@@@@   @@@ ".center(80))
    print(" @@@@@@@@@@@@@@  @@@@@@@@@@  @@ ".center(80))
    print(" @@@@       @@@  @@@@@ @@@@  @@ ".center(80))
    print(" @@@@       @@@  @@@@@@@@@@  @@ ".center(80))
    print(" @@@@      @@@@    @@@@@@@   @@ ".center(80))
    print(" @@@@      @@@@@@@@@@@@@@@@@@@@ ".center(80))
    print(" @@@@       @@@@@@@@@@@@@@@@@@@ ".center(80))
    print(" @@@@       @@@              @@ ".center(80))
    print(" @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ ".center(80))
    print("================================".center(80))
    print("SISTEMA DE GESTIÓN DE PEDIDOS PARA RESTAURANTES".center(80))
    print("TRABAJO PARCIAL".center(80))
    print("================================".center(80))
    print("Curso: PROGRAMACIÓN ORIENTADO A OBJETOS".center(80))
    print("Docente: Juan Alfonso Ramírez Espinoza".center(80))
    print("2025-1".center(80))
    print("--------------------------------".center(80))
    print("Integrantes:".center(80))
    print("Hidalgo Martel, Joseph Edward (U202421665)".center(80))
    print("Huamán Flores, Alexis Miguel (U20241G114)".center(80))
    print("Peña Roña, Antony Jomar (U202421102)".center(80))
    print("Villavicencio Dávila, Ivette Lucero (U20241G010)".center(80))
    print("================================".center(80))
    print("================================".center(80))

# 
def menu():
    print("--" * 30)
    print("<< MENU PRINCIPAL >>".center(60))
    print("--" * 30)
    print("[1] Registrar mesa y mozo 🍽️") 
    print("[2] Solicitar mozo        👨")
    print("[3] Tomar pedido          🍔")
    print("[4] Calcular pago         💵")
    print("[5] Ver reportes          📈")
    print("[6] Salir  ")
    print("--" * 30)
    print("<< ...SISTEMA RESTAURANTE -- BIENVENIDOS ...>>".center(60))
    print("--" * 30)
    
